[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "epicsdev"
version = "3.3.1"
authors = [
  { name="Andrey Sukhanov", email="sukhanov@bnl.gov" },
]
description = "Helper module for creating EPICS PVAccess servers using p4p"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
  "p4p>=4.2.2",
]
[project.urls]
"Homepage" = "https://github.com/eicorg/epicsdev"
"Bug Tracker" = "https://github.com/eicorg/epicsdev"
